name: Bug report
description: Report a problem with discord2sum
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please avoid sharing secrets (tokens, chat IDs).
  - type: input
    id: version
    attributes:
      label: Version / commit
      description: Output of `git rev-parse --short HEAD` or release tag
      placeholder: e.g. 6deef79
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What did you do?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs (redact secrets)
      description: Relevant `journalctl -u discord-voice-summarizer -n 200 --no-pager`
